name: Github Actions Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest
      - name: Compare to moh_v3_template.csv
        shell: bash {0}
        # Script based largely on update_moh_template.sh
        run: |
          python src/clinical_etl/generate_schema.py  --out tmp_template
          diff tmp_template.csv moh_v3_template.csv > tests/moh_diffs.txt
          rm tmp_template.csv
          bytes=$(head -5 tests/moh_diffs.txt | wc -c)
          dd if=tests/moh_diffs.txt bs="$bytes" skip=1 conv=notrunc of=tests/moh_diffs1.txt
          diff tests/moh_diffs1.txt tests/moh_diffs.txt
          if [[ $? == 1 ]]; then echo MoH template checking needs to be updated! See https://github.com/CanDIG/clinical_ETL_code#mapping-template for information.
          exit 1
          fi