name: Github Actions Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest
      - name: Compare moh_template.csv
        shell: bash {0}
        run: |
          python generate_schema.py --url https://raw.githubusercontent.com/CanDIG/katsu/sonchau/uuid_with_fk/chord_metadata_service/mohpackets/docs/schema.yml
          diff template.csv moh_template.csv > curr_diff.txt
          bytes=$(head -5 curr_diff.txt | wc -c)
          dd if=curr_diff.txt bs="$bytes" skip=1 conv=notrunc of=curr_diff.txt
          diff curr_diff.txt test_data/moh_diffs.txt
          if [[ $? == 1 ]]; then echo MoH template checking needs to be updated! See https://github.com/CanDIG/clinical_ETL_code#mapping-template for information.
          exit 1
          fi